name: 'Thank you Action'
description: 'Say "Thank You" to new pull requests'
author: 'daviddcarmona'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'